# // ordes/src/main/resources/application.yaml
server:
  port: 8082

spring:
  application:
    name: orders-service
  datasource:
    url: ${ORDERS_DB_URL:jdbc:postgresql://localhost:5435/orders_db}
    username: ${ORDERS_DB_USER:postgres}
    password: ${ORDERS_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always # Para que busque los archivos schema.sql y data.sql al arrancar
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
