server:
  port: 8081

spring:
  application:
    name: catalogue-service

  datasource:
    url: ${CATALOGUE_DB_URL:jdbc:postgresql://localhost:5434/catalogue_db}
    username: ${CATALOGUE_DB_USER:postgres}
    password: ${CATALOGUE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          # 🔑 Apunta directamente al archivo que acabas de pegar
          public-key-location: classpath:public.pem

  # 🚀 AUTOMATIZACIÓN DE TUS SCRIPTS:
  sql:
    init:
      mode: always
      
  elasticsearch:
    uris: http://localhost:9200

  jpa:
    defer-datasource-initialization: true # 🔴 CRÍTICO: Espera a que termine el esquema antes de meter los datos
    hibernate:
      ddl-auto: none # 👈 CAMBIADO A "none": Ahora tus scripts mandan, así evitamos que Hibernate intente duplicar la tabla

    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}:${random.value}