server:
  port: 8084

spring:
  application:
    name: ms-comms

  # RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

  # SMTP Gmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

# Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Gemini API
gemini:
  api:
    key: ${GEMINI_API_KEY:}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# Actuator — solo health expuesto
management:
  endpoints:
    web:
      exposure:
        include: health, info
